name: aispeak
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  animated_toggle_switch: ^0.8.0
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.1
  flutter_markdown: ^0.6.18+2
  image_picker: ^1.0.7
  lite_rolling_switch: ^1.0.1
  lottie: ^2.7.0
  path: ^1.8.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/robot.png
    - assets/Icons/moon.png
    - assets/animation/AnimationLoading.json
    - assets/Illustration/ask.png
  fonts:
    - family: Urbaninst
      fonts:
        - asset: assets/fonts/Urbanist/static/Urbanist-Regular.ttf
